### PR TITLE
Properly hard-embed the Ace3 framework

### PR DESCRIPTION
**Pull request by Ketho**
- Currently only LibStub is being referenced in the [TOC](http://wow.gamepedia.com/TOC_format), you can reproduce LegionMapZoomer won't work when it's the only addon loaded

```diff
-LegionMapZoomer.lua
-Config.lua
+Ace3\LibStub\LibStub.lua
+Ace3\CallbackHandler-1.0\CallbackHandler-1.0.xml
+Ace3\AceAddon-3.0\AceAddon-3.0.xml
+Ace3\AceEvent-3.0\AceEvent-3.0.xml
+Ace3\AceHook-3.0\AceHook-3.0.xml
+Ace3\AceDB-3.0\AceDB-3.0.xml
+Ace3\AceConsole-3.0\AceConsole-3.0.xml
+Ace3\AceGUI-3.0\AceGUI-3.0.xml
+Ace3\AceConfig-3.0\AceConfig-3.0.xml
 
-Ace3\LibStub\LibStub.lua
+LegionMapZoomer.lua
+Config.lua
```
- AceGUI and CallbackHandler are missing from the Ace3 folder, they are [dependencies](https://forums.wowace.com/showthread.php?t=17903#5) for the other libraries

libs

You can also soft-embed the libraries with the .pkgmeta
https://www.curseforge.com/knowledge-base/world-of-warcraft/527-preparing-the-packagemeta-file
https://www.curseforge.com/docs/packaging

### CODE REVIEW

**Comment by scainburger** [comment]
Thanks for this, I wasn't sure if it was necessary, I assumed not because it was all working properly without it. Obviously this is a little bit of a learning process for me, would you be able to explain why this is necessary over my method? I'll implement this in a small update I'm planning soon.

**Comment by Ketho** [comment]
Because it won't work when it's the only addon loaded, you can try it for yourself

It will only work if some other addon embeds the Ace3 framework and is loaded before LegionMapZoomer

**Comment by scainburger** [comment]
Just pushed 1.1 which implements this, thanks! :)

**Comment by Ketho** [comment]
You're welcome. This is not how repositories work though if you just ([wrongly](https://github.com/scainburger/LegionMapZoomer/commit/ac4d486dfe39c89bc66fbea80ba5817852796da9)) implement it yourself instead of merging the pull request

https://yangsu.github.io/pull-request-tutorial/

**Pull request closed without merging**
